import { JavaScript, TypeScript, Sass, ReactJS, NestJS, Fastify, NodeJS, TypeORM, PostgreSQL, Postman, Figma, VSCode, Docker, Aws } from '../../images/ImageExporter'

export const TexhnologyData = [
    {
        title: 'JavaScript',
        image: JavaScript,
        progress: 75,
        backgroundColor: '#f7df1e',
        textColor: '#fff',
    },
    {
        title: 'TypeScript',
        image: TypeScript,
        progress: 55,
        backgroundColor: '#3178c6',
        textColor: '#fff',
    },
    {
        title: 'Sass',
        image: Sass,
        progress: 90,
        backgroundColor: '#cc689a',
        textColor: '#fff',
    },
    {
        title: 'Break-first',
        image: null,
        progress: 0,
        backgroundColor: '',
        textColor: '',
    },
    {
        title: 'ReactJS',
        image: ReactJS,
        progress: 85,
        backgroundColor: '#55c2de',
        textColor: '#fff',
    },
    {
        title: 'NestJS',
        image: NestJS,
        progress: 70,
        backgroundColor: '#e0234e',
        textColor: '#fff',
    },
    {
        title: 'Fastify',
        image: Fastify,
        progress: 85,
        backgroundColor: '#000',
        textColor: '#fff',
    },
    {
        title: 'NodeJS',
        image: NodeJS,
        progress: 80,
        backgroundColor: '#84cd2a',
        textColor: '#fff',
    },
    {
        title: 'Break-seccond',
        image: null,
        progress: 0,
        backgroundColor: '',
        textColor: '',
    },
    {
        title: 'TypeORM',
        image: TypeORM,
        progress: 65,
        backgroundColor: '#f3af3d',
        textColor: '#fff',
    },
    {
        title: 'PostgreSQL',
        image: PostgreSQL,
        progress: 90,
        backgroundColor: '#336791',
        textColor: '#fff',
    },
    {
        title: 'Postman',
        image: Postman,
        progress: 95,
        backgroundColor: '#ff6c37',
        textColor: '#fff',
    },
    {
        title: 'Figma',
        image: Figma,
        progress: 45,
        backgroundColor: '#a259ff',
        textColor: '#fff',
    },
    {
        title: 'Break-third',
        image: null,
        progress: 0,
        backgroundColor: '',
        textColor: '',
    },
    {
        title: 'VSCode',
        image: VSCode,
        progress: 85,
        backgroundColor: '#008eda',
        textColor: '#fff',
    },
    {
        title: 'Docker',
        image: Docker,
        progress: 60,
        backgroundColor: '#2496ed',
        textColor: '#fff',
    },
    {
        title: 'Aws',
        image: Aws,
        progress: 50,
        backgroundColor: '#ff9900',
        textColor: '#fff',
    }
]